# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import user_message_pb2 as user__message__pb2


class UserMessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMessageList = channel.unary_unary(
                '/UserMessage/GetMessageList',
                request_serializer=user__message__pb2.GetMessageListRequest.SerializeToString,
                response_deserializer=user__message__pb2.MessageListResponse.FromString,
                )
        self.CreateMessage = channel.unary_unary(
                '/UserMessage/CreateMessage',
                request_serializer=user__message__pb2.CreateMessageRequest.SerializeToString,
                response_deserializer=user__message__pb2.MessageResponse.FromString,
                )
        self.UpdateMessage = channel.unary_unary(
                '/UserMessage/UpdateMessage',
                request_serializer=user__message__pb2.UpdateMessageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteMessage = channel.unary_unary(
                '/UserMessage/DeleteMessage',
                request_serializer=user__message__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetMessageDetail = channel.unary_unary(
                '/UserMessage/GetMessageDetail',
                request_serializer=user__message__pb2.GetMessageDetailRequest.SerializeToString,
                response_deserializer=user__message__pb2.MessageResponse.FromString,
                )


class UserMessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMessageList(self, request, context):
        """获取消息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessage(self, request, context):
        """创建消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """更新消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """删除消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageDetail(self, request, context):
        """消息详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserMessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMessageList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageList,
                    request_deserializer=user__message__pb2.GetMessageListRequest.FromString,
                    response_serializer=user__message__pb2.MessageListResponse.SerializeToString,
            ),
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=user__message__pb2.CreateMessageRequest.FromString,
                    response_serializer=user__message__pb2.MessageResponse.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=user__message__pb2.UpdateMessageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=user__message__pb2.DeleteMessageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMessageDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageDetail,
                    request_deserializer=user__message__pb2.GetMessageDetailRequest.FromString,
                    response_serializer=user__message__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserMessage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserMessage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMessageList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserMessage/GetMessageList',
            user__message__pb2.GetMessageListRequest.SerializeToString,
            user__message__pb2.MessageListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserMessage/CreateMessage',
            user__message__pb2.CreateMessageRequest.SerializeToString,
            user__message__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserMessage/UpdateMessage',
            user__message__pb2.UpdateMessageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserMessage/DeleteMessage',
            user__message__pb2.DeleteMessageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessageDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserMessage/GetMessageDetail',
            user__message__pb2.GetMessageDetailRequest.SerializeToString,
            user__message__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
