version: '3'

networks:
  python:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.1/24

services:
  user-srv:
    build:
      context: ./user_srv
    environment:
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_NAMESPACE: "${USER_NACOS_NAMESPACE}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${USER_NACOS_DATA_ID}"
      NACOS_GROUP: "${USER_NACOS_GROUP}"
    networks:
      - python
    volumes:
      - ./common:/code/common
  company-srv:
    build:
      context: ./company_srv
    environment:
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"

      NACOS_NAMESPACE: "${COMPANY_NACOS_NAMESPACE}"
      NACOS_DATA_ID: "${COMPANY_NACOS_DATA_ID}"
      NACOS_GROUP: "${COMPANY_NACOS_GROUP}"
    networks:
      - python
    volumes:
      - ./common:/code/common