# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\"Q\n\x12\x43ountResumeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\x05\"$\n\x13\x43ountResumeResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32P\n\x14ResumeCounterService\x12\x38\n\x0b\x43ountResume\x12\x13.CountResumeRequest\x1a\x14.CountResumeResponseB\nZ\x08../protob\x06proto3')



_COUNTRESUMEREQUEST = DESCRIPTOR.message_types_by_name['CountResumeRequest']
_COUNTRESUMERESPONSE = DESCRIPTOR.message_types_by_name['CountResumeResponse']
CountResumeRequest = _reflection.GeneratedProtocolMessageType('CountResumeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRESUMEREQUEST,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:CountResumeRequest)
  })
_sym_db.RegisterMessage(CountResumeRequest)

CountResumeResponse = _reflection.GeneratedProtocolMessageType('CountResumeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRESUMERESPONSE,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:CountResumeResponse)
  })
_sym_db.RegisterMessage(CountResumeResponse)

_RESUMECOUNTERSERVICE = DESCRIPTOR.services_by_name['ResumeCounterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _COUNTRESUMEREQUEST._serialized_start=17
  _COUNTRESUMEREQUEST._serialized_end=98
  _COUNTRESUMERESPONSE._serialized_start=100
  _COUNTRESUMERESPONSE._serialized_end=136
  _RESUMECOUNTERSERVICE._serialized_start=138
  _RESUMECOUNTERSERVICE._serialized_end=218
# @@protoc_insertion_point(module_scope)
