# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import resume_pb2 as resume__pb2


class ResumeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResumeList = channel.unary_unary(
                '/Resume/GetResumeList',
                request_serializer=resume__pb2.GetResumeListRequest.SerializeToString,
                response_deserializer=resume__pb2.GetResumeListResponse.FromString,
                )
        self.CreateResume = channel.unary_unary(
                '/Resume/CreateResume',
                request_serializer=resume__pb2.CreateResumeRequest.SerializeToString,
                response_deserializer=resume__pb2.ResumeResponse.FromString,
                )
        self.UpdateResume = channel.unary_unary(
                '/Resume/UpdateResume',
                request_serializer=resume__pb2.UpdateResumeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteResume = channel.unary_unary(
                '/Resume/DeleteResume',
                request_serializer=resume__pb2.DeleteResumeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ResumeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResumeList(self, request, context):
        """获取简历列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResume(self, request, context):
        """创建简历
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResume(self, request, context):
        """更新简历
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResume(self, request, context):
        """删除简历
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResumeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResumeList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResumeList,
                    request_deserializer=resume__pb2.GetResumeListRequest.FromString,
                    response_serializer=resume__pb2.GetResumeListResponse.SerializeToString,
            ),
            'CreateResume': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResume,
                    request_deserializer=resume__pb2.CreateResumeRequest.FromString,
                    response_serializer=resume__pb2.ResumeResponse.SerializeToString,
            ),
            'UpdateResume': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResume,
                    request_deserializer=resume__pb2.UpdateResumeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteResume': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResume,
                    request_deserializer=resume__pb2.DeleteResumeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Resume', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Resume(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResumeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Resume/GetResumeList',
            resume__pb2.GetResumeListRequest.SerializeToString,
            resume__pb2.GetResumeListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Resume/CreateResume',
            resume__pb2.CreateResumeRequest.SerializeToString,
            resume__pb2.ResumeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Resume/UpdateResume',
            resume__pb2.UpdateResumeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Resume/DeleteResume',
            resume__pb2.DeleteResumeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
