# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\"\x84\x01\n\x10\x43ountPostRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12-\n\x06search\x18\x02 \x03(\x0b\x32\x1d.CountPostRequest.SearchEntry\x1a-\n\x0bSearchEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9d\x01\n\x14\x43ountUserPostRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12\x0f\n\x07post_id\x18\x02 \x01(\x03\x12\x31\n\x06search\x18\x03 \x03(\x0b\x32!.CountUserPostRequest.SearchEntry\x1a-\n\x0bSearchEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x15\x43ountUserPostResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"\"\n\x11\x43ountPostResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\x8b\x01\n\x15RecruitCounterService\x12\x32\n\tCountPost\x12\x11.CountPostRequest\x1a\x12.CountPostResponse\x12>\n\rCountUserPost\x12\x15.CountUserPostRequest\x1a\x16.CountUserPostResponseB\nZ\x08../protob\x06proto3')



_COUNTPOSTREQUEST = DESCRIPTOR.message_types_by_name['CountPostRequest']
_COUNTPOSTREQUEST_SEARCHENTRY = _COUNTPOSTREQUEST.nested_types_by_name['SearchEntry']
_COUNTUSERPOSTREQUEST = DESCRIPTOR.message_types_by_name['CountUserPostRequest']
_COUNTUSERPOSTREQUEST_SEARCHENTRY = _COUNTUSERPOSTREQUEST.nested_types_by_name['SearchEntry']
_COUNTUSERPOSTRESPONSE = DESCRIPTOR.message_types_by_name['CountUserPostResponse']
_COUNTPOSTRESPONSE = DESCRIPTOR.message_types_by_name['CountPostResponse']
CountPostRequest = _reflection.GeneratedProtocolMessageType('CountPostRequest', (_message.Message,), {

  'SearchEntry' : _reflection.GeneratedProtocolMessageType('SearchEntry', (_message.Message,), {
    'DESCRIPTOR' : _COUNTPOSTREQUEST_SEARCHENTRY,
    '__module__' : 'counter_pb2'
    # @@protoc_insertion_point(class_scope:CountPostRequest.SearchEntry)
    })
  ,
  'DESCRIPTOR' : _COUNTPOSTREQUEST,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:CountPostRequest)
  })
_sym_db.RegisterMessage(CountPostRequest)
_sym_db.RegisterMessage(CountPostRequest.SearchEntry)

CountUserPostRequest = _reflection.GeneratedProtocolMessageType('CountUserPostRequest', (_message.Message,), {

  'SearchEntry' : _reflection.GeneratedProtocolMessageType('SearchEntry', (_message.Message,), {
    'DESCRIPTOR' : _COUNTUSERPOSTREQUEST_SEARCHENTRY,
    '__module__' : 'counter_pb2'
    # @@protoc_insertion_point(class_scope:CountUserPostRequest.SearchEntry)
    })
  ,
  'DESCRIPTOR' : _COUNTUSERPOSTREQUEST,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:CountUserPostRequest)
  })
_sym_db.RegisterMessage(CountUserPostRequest)
_sym_db.RegisterMessage(CountUserPostRequest.SearchEntry)

CountUserPostResponse = _reflection.GeneratedProtocolMessageType('CountUserPostResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTUSERPOSTRESPONSE,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:CountUserPostResponse)
  })
_sym_db.RegisterMessage(CountUserPostResponse)

CountPostResponse = _reflection.GeneratedProtocolMessageType('CountPostResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTPOSTRESPONSE,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:CountPostResponse)
  })
_sym_db.RegisterMessage(CountPostResponse)

_RECRUITCOUNTERSERVICE = DESCRIPTOR.services_by_name['RecruitCounterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _COUNTPOSTREQUEST_SEARCHENTRY._options = None
  _COUNTPOSTREQUEST_SEARCHENTRY._serialized_options = b'8\001'
  _COUNTUSERPOSTREQUEST_SEARCHENTRY._options = None
  _COUNTUSERPOSTREQUEST_SEARCHENTRY._serialized_options = b'8\001'
  _COUNTPOSTREQUEST._serialized_start=18
  _COUNTPOSTREQUEST._serialized_end=150
  _COUNTPOSTREQUEST_SEARCHENTRY._serialized_start=105
  _COUNTPOSTREQUEST_SEARCHENTRY._serialized_end=150
  _COUNTUSERPOSTREQUEST._serialized_start=153
  _COUNTUSERPOSTREQUEST._serialized_end=310
  _COUNTUSERPOSTREQUEST_SEARCHENTRY._serialized_start=105
  _COUNTUSERPOSTREQUEST_SEARCHENTRY._serialized_end=150
  _COUNTUSERPOSTRESPONSE._serialized_start=312
  _COUNTUSERPOSTRESPONSE._serialized_end=350
  _COUNTPOSTRESPONSE._serialized_start=352
  _COUNTPOSTRESPONSE._serialized_end=386
  _RECRUITCOUNTERSERVICE._serialized_start=389
  _RECRUITCOUNTERSERVICE._serialized_end=528
# @@protoc_insertion_point(module_scope)
