# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import counter_pb2 as counter__pb2


class RecruitCounterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountPost = channel.unary_unary(
                '/RecruitCounterService/CountPost',
                request_serializer=counter__pb2.CountPostRequest.SerializeToString,
                response_deserializer=counter__pb2.CountPostResponse.FromString,
                )
        self.CountUserPost = channel.unary_unary(
                '/RecruitCounterService/CountUserPost',
                request_serializer=counter__pb2.CountUserPostRequest.SerializeToString,
                response_deserializer=counter__pb2.CountUserPostResponse.FromString,
                )


class RecruitCounterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountPost(self, request, context):
        """统计简历
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountUserPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecruitCounterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountPost': grpc.unary_unary_rpc_method_handler(
                    servicer.CountPost,
                    request_deserializer=counter__pb2.CountPostRequest.FromString,
                    response_serializer=counter__pb2.CountPostResponse.SerializeToString,
            ),
            'CountUserPost': grpc.unary_unary_rpc_method_handler(
                    servicer.CountUserPost,
                    request_deserializer=counter__pb2.CountUserPostRequest.FromString,
                    response_serializer=counter__pb2.CountUserPostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecruitCounterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecruitCounterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecruitCounterService/CountPost',
            counter__pb2.CountPostRequest.SerializeToString,
            counter__pb2.CountPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CountUserPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecruitCounterService/CountUserPost',
            counter__pb2.CountUserPostRequest.SerializeToString,
            counter__pb2.CountUserPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
