# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import user_post_pb2 as user__post__pb2


class UserPostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserPostList = channel.unary_unary(
                '/UserPost/GetUserPostList',
                request_serializer=user__post__pb2.GetUserPostListRequest.SerializeToString,
                response_deserializer=user__post__pb2.UserPostListResponse.FromString,
                )
        self.CreateUserPost = channel.unary_unary(
                '/UserPost/CreateUserPost',
                request_serializer=user__post__pb2.CreateUserPostRequest.SerializeToString,
                response_deserializer=user__post__pb2.UserPostResponse.FromString,
                )
        self.UpdateUserPost = channel.unary_unary(
                '/UserPost/UpdateUserPost',
                request_serializer=user__post__pb2.UpdateUserPostRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteUserPost = channel.unary_unary(
                '/UserPost/DeleteUserPost',
                request_serializer=user__post__pb2.DeleteUserPostRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetUserPostDetail = channel.unary_unary(
                '/UserPost/GetUserPostDetail',
                request_serializer=user__post__pb2.GetUserPostDetailRequest.SerializeToString,
                response_deserializer=user__post__pb2.UserPostResponse.FromString,
                )
        self.BatchUpdateUserPost = channel.unary_unary(
                '/UserPost/BatchUpdateUserPost',
                request_serializer=user__post__pb2.BatchUpdateUserPostRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class UserPostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserPostList(self, request, context):
        """获取岗位 投递列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserPost(self, request, context):
        """投递简历
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserPost(self, request, context):
        """修改投递
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserPost(self, request, context):
        """取消投递
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPostDetail(self, request, context):
        """获取投递详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdateUserPost(self, request, context):
        """批量修改状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserPostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserPostList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPostList,
                    request_deserializer=user__post__pb2.GetUserPostListRequest.FromString,
                    response_serializer=user__post__pb2.UserPostListResponse.SerializeToString,
            ),
            'CreateUserPost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserPost,
                    request_deserializer=user__post__pb2.CreateUserPostRequest.FromString,
                    response_serializer=user__post__pb2.UserPostResponse.SerializeToString,
            ),
            'UpdateUserPost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserPost,
                    request_deserializer=user__post__pb2.UpdateUserPostRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteUserPost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserPost,
                    request_deserializer=user__post__pb2.DeleteUserPostRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUserPostDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPostDetail,
                    request_deserializer=user__post__pb2.GetUserPostDetailRequest.FromString,
                    response_serializer=user__post__pb2.UserPostResponse.SerializeToString,
            ),
            'BatchUpdateUserPost': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdateUserPost,
                    request_deserializer=user__post__pb2.BatchUpdateUserPostRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserPost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserPost(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserPostList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserPost/GetUserPostList',
            user__post__pb2.GetUserPostListRequest.SerializeToString,
            user__post__pb2.UserPostListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUserPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserPost/CreateUserPost',
            user__post__pb2.CreateUserPostRequest.SerializeToString,
            user__post__pb2.UserPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserPost/UpdateUserPost',
            user__post__pb2.UpdateUserPostRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserPost/DeleteUserPost',
            user__post__pb2.DeleteUserPostRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserPostDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserPost/GetUserPostDetail',
            user__post__pb2.GetUserPostDetailRequest.SerializeToString,
            user__post__pb2.UserPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchUpdateUserPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserPost/BatchUpdateUserPost',
            user__post__pb2.BatchUpdateUserPostRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
