# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\",\n\nUserIdList\x12\x0f\n\x07user_id\x18\x01 \x03(\x03\x12\r\n\x05total\x18\x02 \x01(\x03\x42\nZ\x08../protob\x06proto3')



_USERIDLIST = DESCRIPTOR.message_types_by_name['UserIdList']
UserIdList = _reflection.GeneratedProtocolMessageType('UserIdList', (_message.Message,), {
  'DESCRIPTOR' : _USERIDLIST,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:UserIdList)
  })
_sym_db.RegisterMessage(UserIdList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _USERIDLIST._serialized_start=16
  _USERIDLIST._serialized_end=60
# @@protoc_insertion_point(module_scope)
